### ISSUE TITLE
Web View crash during 3ds payment

### ISSUE THREAD

**Issue by Hardenn** [yandex-money/yandex-checkout-payments-swift#10] opened 2018-08-16 15:40 UTC
Hey!

We've got crash in web view while 3ds process. It appeared just once on Yandex.Kassa test server.

- OS Version: 11.4.0 
- Device: iPhone X
- [URL we tried to open](https:\/\/money.yandex.ru\/api-pages\/v3\/3ds?acsUri=https%3A%2F%2Fdemo-scrat.yamoney.ru%3A8443%2Fmerchant-test-card-stub%2F3ds%3Ftes11%3D1%26amp%3Btest2%3D2&MD=1534261606604-677374840537400364&PaReq=Q1VSUkVOQ1k9UlVSJlRFUk1JTkFMPTk5OTk5OCZFWFBfWUVBUj0yNSZQX1NJR049YTFmMDU0MzQxNTY3MjRiMGE3ZTA5YzUwMjk4MzIxNjM4NThjODcwYyZSRVNQT05TRV9SUk49Mzc0ODQwNDkwMzM3JkVNQUlMPW5vcmVwbHklNDBtb25leS55YW5kZXgucnUmTUVSQ0hfTkFNRT1ZTSZERVNDPTIzMDUwZDI2LTAwMGYtNTAwMC05MDAwLTEwY2I4YmE1MzhhZiZSRVNQT05TRV9BVVRIQ09ERT00ODg0ODkmTUVSQ0hBTlQ9NzkwMzY3Njg2MjE5OTk5JkNBUkQ9NTU1NTU1NTU1NTU1NDQ3NyZOQU1FPSZPUkRFUj00OTQ4OTY2Mjk3Jk1FUkNIX1VSTD1tb25leS55YW5kZXgucnUmQU1PVU5UPTM5OTg5LjcxJkJBQ0tSRUY9aHR0cHMlM0ElMkYlMkZ3d3cuc29nbGFzaWUucnUlMkYmVElNRVNUQU1QPTIwMTgwODE0MTU0NjQ2JlRSVFlQRT0wJkVYUD0xMiZDVkMyPTM2NCZOT05DRT0xMjM0NTY3ODkwQUJDREVGNTk1OWMzMmVmOTE2OQ%3D%3D&TermUrl=https%3A%2F%2Fpaymentcard.yamoney.ru%3A443%2Fgates%2Fmb3dsdemoprovider)

**Fabric screenshot:**

![2018-08-16 18 33 36](https://user-images.githubusercontent.com/1327323/44218743-061aaf80-a183-11e8-9be0-6eb1ca275d5c.jpg)

**Fabric text log:**

[yandex-kassa-sdk-web-view-crash-14-08-18.txt](https://github.com/yandex-money/yandex-checkout-payments-swift/files/2294227/yandex-kassa-sdk-web-view-crash-14-08-18.txt)

**Comment by oltv00** [comment] 2019-02-08 13:13
@Hardenn 

Unfortunately, we were unable to reproduce the problem.
Was the problem repeated again?

**Comment by Hardenn** [comment] 2019-02-08 13:49
@oltv00 No, there're no more crashes like this.

**Comment by oltv00** [comment] 2019-02-08 14:24
@Hardenn 
Since the problem could not be reproduced, I close the issue.

**Closed by oltv00** 2019-02-08 14:24 UTC
